baseURL = 'http://blog.sunbk201.site/'
languageCode = 'zh-cn'
title = "SunBK201's Blog"

[services]
  [services.googleAnalytics]
    id = 'G-GELV24FLB2'

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

[outputFormats]
  [outputFormats.RSS]
    baseName = "feed"
    mediatype = "application/rss"
